#pragma once

#include <libraw.h>

namespace HurlbertVisionLab {
	namespace LibRawWrapper {
		namespace Native
		{
			public enum class CameraMaker
			{
				Unknown = LIBRAW_CAMERAMAKER_Unknown,
				Agfa = LIBRAW_CAMERAMAKER_Agfa,
				Alcatel = LIBRAW_CAMERAMAKER_Alcatel,
				Apple = LIBRAW_CAMERAMAKER_Apple,
				Aptina = LIBRAW_CAMERAMAKER_Aptina,
				AVT = LIBRAW_CAMERAMAKER_AVT,
				Baumer = LIBRAW_CAMERAMAKER_Baumer,
				Broadcom = LIBRAW_CAMERAMAKER_Broadcom,
				Canon = LIBRAW_CAMERAMAKER_Canon,
				Casio = LIBRAW_CAMERAMAKER_Casio,
				CINE = LIBRAW_CAMERAMAKER_CINE,
				Clauss = LIBRAW_CAMERAMAKER_Clauss,
				Contax = LIBRAW_CAMERAMAKER_Contax,
				Creative = LIBRAW_CAMERAMAKER_Creative,
				DJI = LIBRAW_CAMERAMAKER_DJI,
				DXO = LIBRAW_CAMERAMAKER_DXO,
				Epson = LIBRAW_CAMERAMAKER_Epson,
				Foculus = LIBRAW_CAMERAMAKER_Foculus,
				Fujifilm = LIBRAW_CAMERAMAKER_Fujifilm,
				Generic = LIBRAW_CAMERAMAKER_Generic,
				Gione = LIBRAW_CAMERAMAKER_Gione,
				GITUP = LIBRAW_CAMERAMAKER_GITUP,
				Google = LIBRAW_CAMERAMAKER_Google,
				GoPro = LIBRAW_CAMERAMAKER_GoPro,
				Hasselblad = LIBRAW_CAMERAMAKER_Hasselblad,
				HTC = LIBRAW_CAMERAMAKER_HTC,
				IMobile = LIBRAW_CAMERAMAKER_I_Mobile,
				Imacon = LIBRAW_CAMERAMAKER_Imacon,
				JK_Imaging = LIBRAW_CAMERAMAKER_JK_Imaging,
				Kodak = LIBRAW_CAMERAMAKER_Kodak,
				Konica = LIBRAW_CAMERAMAKER_Konica,
				Leaf = LIBRAW_CAMERAMAKER_Leaf,
				Leica = LIBRAW_CAMERAMAKER_Leica,
				Lenovo = LIBRAW_CAMERAMAKER_Lenovo,
				LG = LIBRAW_CAMERAMAKER_LG,
				Logitech = LIBRAW_CAMERAMAKER_Logitech,
				Mamiya = LIBRAW_CAMERAMAKER_Mamiya,
				Matrix = LIBRAW_CAMERAMAKER_Matrix,
				Meizu = LIBRAW_CAMERAMAKER_Meizu,
				Micron = LIBRAW_CAMERAMAKER_Micron,
				Minolta = LIBRAW_CAMERAMAKER_Minolta,
				Motorola = LIBRAW_CAMERAMAKER_Motorola,
				NGM = LIBRAW_CAMERAMAKER_NGM,
				Nikon = LIBRAW_CAMERAMAKER_Nikon,
				Nokia = LIBRAW_CAMERAMAKER_Nokia,
				Olympus = LIBRAW_CAMERAMAKER_Olympus,
				OmniVison = LIBRAW_CAMERAMAKER_OmniVison,
				Panasonic = LIBRAW_CAMERAMAKER_Panasonic,
				Parrot = LIBRAW_CAMERAMAKER_Parrot,
				Pentax = LIBRAW_CAMERAMAKER_Pentax,
				PhaseOne = LIBRAW_CAMERAMAKER_PhaseOne,
				PhotoControl = LIBRAW_CAMERAMAKER_PhotoControl,
				Photron = LIBRAW_CAMERAMAKER_Photron,
				Pixelink = LIBRAW_CAMERAMAKER_Pixelink,
				Polaroid = LIBRAW_CAMERAMAKER_Polaroid,
				RED = LIBRAW_CAMERAMAKER_RED,
				Ricoh = LIBRAW_CAMERAMAKER_Ricoh,
				Rollei = LIBRAW_CAMERAMAKER_Rollei,
				RoverShot = LIBRAW_CAMERAMAKER_RoverShot,
				Samsung = LIBRAW_CAMERAMAKER_Samsung,
				Sigma = LIBRAW_CAMERAMAKER_Sigma,
				Sinar = LIBRAW_CAMERAMAKER_Sinar,
				SMaL = LIBRAW_CAMERAMAKER_SMaL,
				Sony = LIBRAW_CAMERAMAKER_Sony,
				STMicro = LIBRAW_CAMERAMAKER_ST_Micro,
				THL = LIBRAW_CAMERAMAKER_THL,
				VLUU = LIBRAW_CAMERAMAKER_VLUU,
				Xiaomi = LIBRAW_CAMERAMAKER_Xiaomi,
				XIAOYI = LIBRAW_CAMERAMAKER_XIAOYI,
				YI = LIBRAW_CAMERAMAKER_YI,
				Yuneec = LIBRAW_CAMERAMAKER_Yuneec,
				Zeiss = LIBRAW_CAMERAMAKER_Zeiss,
				//OnePlus = LIBRAW_CAMERAMAKER_OnePlus,
				//ISG = LIBRAW_CAMERAMAKER_ISG,
				//VIVO = LIBRAW_CAMERAMAKER_VIVO,
				//HMDGlobal = LIBRAW_CAMERAMAKER_HMD_Global,
				//Huawei = LIBRAW_CAMERAMAKER_HUAWEI,
			};
		}
	}
}